environment:
  DOCKER_USER_NAME: Neu
  DOCKER_PASSWORD: 114514

timeout_in: 24h

windows_docker_builder:
  use_compute_credits: true
  platform: windows
  os_version: 2019
  info_script:
    - docker version
    - docker info
  pull_script: docker pull mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
  build_core_script: docker build -m 2GB --tag cirrusci/windowsservercore:2019 --tag cirrusci/windowsservercore:2019-%CIRRUS_TAG% windowsservercore
  build_visualstudio_script: docker build -m 2GB --tag cirrusci/windowsservercore:visualstudio2019 --tag cirrusci/windowsservercore:visualstudio2019-%CIRRUS_TAG% contrib/visualstudio2019
  build_cmake_script: docker build -m 2GB --tag cirrusci/windowsservercore:cmake --tag cirrusci/windowsservercore:cmake-%CIRRUS_TAG% contrib/cmake
  matrix:
    - name: Push
      only_if: $CIRRUS_TAG != ''
      push_script: push_docker.bat
    - name: Build
      only_if: $CIRRUS_TAG == ''
